set_property SRC_FILE_INFO {cfile:C:/Temp/Manager_Demo/Test/Test.srcs/constrs_1/imports/Test/Cora-Z7-10-Master.xdc rfile:../../../Test.srcs/constrs_1/imports/Test/Cora-Z7-10-Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H16 IOSTANDARD LVCMOS33} [get_ports clk]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U14 IOSTANDARD LVCMOS33} [get_ports reset]
